server:
   port: 8001
eureka:
   instance:
      instance-id: ${spring.application.name}
      hostname: localhost
      statusPageUrlPath: /actuator/health
   client:
      service-url:
         defaultZone: http://localhost:8761/eureka
spring:
   application:
      name: ms-product
   datasource:
      url: jdbc:postgresql://localhost:5432/ecommerce
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
   jpa: 
      hibernate:
         ddl-auto: update