server:
   port: 8004
eureka:
   instance:
      instance-id: ${spring.application.name}
      hostname: localhost
      statusPageUrlPath: /actuator/health
   client:
      service-url:
         defaultZone: http://localhost:8761/eureka
spring:
   application:
      name: ms-authentication
   datasource:
      url: jdbc:postgresql://localhost:5432/ecommerce
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
   jpa: 
      hibernate:
         ddl-auto: update
secret:
   key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b 