server:
   port: 8005
eureka:
   instance:
      instance-id: ${spring.application.name}
      hostname: localhost
      statusPageUrlPath: /actuator/health
   client:
      service-url:
         defaultZone: http://localhost:8761/eureka
spring:
   application:
      name: ms-mail
   kafka:
      consumer:
         bootstrap-servers: localhost:29092
         group-id: group_id
         auto-offset-reset: earliest
         key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
         value-deserializer: com.github.ecommerce.deserializer.OrderMailDeserializer
topic:
   name:
      consumer: order-mail